i = 123
j = 0
k = -234

print(111)
print(-123,-i)
print(123,+i)
print(-124,~i)
print(True,bool(i))
print(False,not i)
print(123,int(i))
print(123,abs(i))
print(123,hash(i))

print(112)
print(0,-j)
print(0,+j)
print(-1,~j)
print(False,bool(j))
print(True,not j)
print(0,int(j))
print(0,abs(j))
print(0,hash(j))

print(113)
print(234,-k)
print(-234,+k)
print(233,~k)
print(True,bool(k))
print(False,not k)
print(-234,int(k))
print(234,abs(k))
print(-234,hash(k))

print(114)
print(bool(b''))
print(bool(b'abc'))
print(bool(b'abcdefghijklmnopqrstuvwxyz'))
print(hash(b''))
print(hash(b'abc'))
print(hash(b'abcdefghijklmnopqrstuvwxyz'))

print(115)
print(bool(''))
print(bool('abc'))
print(bool('abcdefghijklmnopqrstuvwxyz'))
print(hash(''))
print(hash('abc'))
print(hash('abcdefghijklmnopqrstuvwxyz'))

print(116)
print(False,not True)
print(True,not False)
print(1,int(True))
print(0,int(False))
print(True,bool(True))
print(False,bool(False))
print(1,hash(True))
print(0,hash(False))
